# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171019_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='core.User'),
        ),
        migrations.AddField(
            model_name='messagelike',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Message'),
        ),
        migrations.AddField(
            model_name='messagelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(through='core.MessageLike', to='core.User'),
        ),
    ]
