# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171019_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.BinaryField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Message')),
            ],
        ),
    ]
